### ISSUE TITLE
🎨 Drag & Drop UX İyileştirmeleri

### ISSUE THREAD

**Issue by hllbr** [hllbr/active-shooter-tower-defense#24]
# 🎨 Drag & Drop UX İyileştirmeleri

## 📝 Problem Açıklaması
Kule taşıma (drag & drop) sırasında kullanıcı belirsizlik yaşıyor. Görsel feedback yetersiz ve hangi slot'lara taşıyabileceği net değil.

## 🔍 Mevcut Durum
- **Konum**: `src/components/GameBoard.tsx` - drag handlers
- **Problem**: Yetersiz görsel feedback
- **Etki**: Kafa karışıklığı, yanlış hamle yapma

### 1. **Görsel Feedback Eksiklikleri**
- [ ] Valid drop zone highlighting yok
- [ ] Invalid drop zone indication yok  
- [ ] Drag preview animation yetersiz
- [ ] Success/error feedback yok

### 2. **Drag State Belirsizlikleri**
- [ ] Hangi tower'ların taşınabileceği belirsiz
- [ ] Energy cost bilgisi görünmüyor
- [ ] Cooldown durumu net değil

### 3. **Mobile Uyumluluk**
- [ ] Touch events desteklenmiyor
- [ ] Responsive drag & drop yok

### 1. **Visual Feedback Sistemi**
```typescript
interface DragState {
  isDragging: boolean;
  draggedTower: Tower | null;
  validDropZones: number[];
  hoveredSlot: number | null;
}
```

### 2. **Drop Zone Highlighting**
- ✅ **Valid zones**: Yeşil highlight + pulsing effect
- ❌ **Invalid zones**: Kırmızı highlight + shake effect
- 💰 **Cost indicator**: Energy cost overlay
- ⏱️ **Cooldown**: Timer indicator

### 3. **Drag Preview**
- Ghost tower preview
- Smooth transitions
- Range indicator
- Target preview

### 4. **Smart Tooltips**
- Hover'da detaylı bilgi
- Drag sırasında context info
- Error messages

### CSS Animations
```css
.drop-zone-valid {
  background: rgba(34, 197, 94, 0.2);
  border: 2px dashed #22c55e;
  animation: pulse 1s infinite;
}

.drop-zone-invalid {
  background: rgba(239, 68, 68, 0.2);
  border: 2px dashed #ef4444;
  animation: shake 0.5s ease-in-out;
}
```

### Interaction States
```typescript
const dragHandlers = {
  onDragStart: (tower: Tower) => void,
  onDragOver: (slotId: number) => void,
  onDragLeave: () => void,
  onDrop: (targetSlot: number) => void,
  onDragEnd: () => void
};
```

## 📱 Mobile Considerations
- Touch event handlers
- Long press to drag
- Visual feedback for touch
- Haptic feedback (if available)

## 🏷️ Labels
`ui/ux`, `enhancement`, `accessibility`, `mobile`

## ⚖️ Priority
**MEDIUM** - Kullanıcı deneyimini önemli ölçüde iyileştirecek
