### ISSUE TITLE
Command Center S Button Design

### ISSUE THREAD

**Issue by hllbr** [hllbr/active-shooter-tower-defense#60]
# 🎯 STRATEGIC COMMAND CENTER (S Button) - Tasarım Dokümantasyonu

## **Öncelik**: YÜKSEK 🟡  
**Durum**: Mevcut yükseltmelerin görünür olmaması  
**Etki**: Oyuncu progression'ını takip edemiyor  
**Hedef**: Kapsamlı durum özeti ekranı  

---

### **Kullanıcının Sorunu**
> "Aldığımız ve tekrar alamayacağımız yükseltmeler görünmesin onun yerine mevcut yükseltmelerimizin neler olduğunu göreceğimiz yeni bir ekran tasarlayalım. Mesela ateş gücünde şu şu değerler sahibiz, 10 kez kule savunmasının x değerini aldık ve seriyi tamamladık gibi bilgilerin de olduğu açıklayıcı ve S butonuyla açılan bir ekran daha geliştirelim."

### **Problem Analizi**
- ❌ Satın alınan yükseltmeler görünmeye devam ediyor (karışıklık)
- ❌ Mevcut build power'ın özeti yok
- ❌ Tamamlanan serilerin takibi yok
- ❌ Strategic overview eksik
- ❌ Progress tracking yetersiz

---

### **Ana Sekmeler**
```typescript
interface CommandCenterTabs {
  overview: 'Genel Bakış';
  builds: 'Mevcut Build';
  achievements: 'Başarımlar';
  statistics: 'İstatistikler';
  research: 'Araştırma';
  strategy: 'Strateji Önerileri';
}
```

---

### **Mevcut Güç Seviyesi**
```typescript
interface PowerOverview {
  // Toplam savaş gücü
  totalCombatPower: number;
  // Ana statistikler
  primaryStats: {
    firepower: {
      current: number;
      next_milestone: number;
      progress: number; // 0-100%
      rank: 'Rookie' | 'Veteran' | 'Elite' | 'Master' | 'Legend';
    };
    defense: {
      current: number;
      shieldStrength: number;
      wallLevel: number;
      coverage: number; // %
    };
    economy: {
      goldPerWave: number;
      efficiency: number; // %
      investments: number;
    };
    special: {
      energyCapacity: number;
      actionPoints: number;
      abilities: string[];
    };
  };
}
```

### **Görsel Tasarım - Genel Bakış**
```css
.overview-dashboard {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24px;
  padding: 20px;
}

.power-meter {
  background: linear-gradient(135deg, #0a0a0a, #1a1a2e);
  border: 2px solid #ffd700;
  border-radius: 16px;
  padding: 20px;
}

.stat-ring {
  position: relative;
  width: 120px;
  height: 120px;
  margin: 0 auto;
}

.stat-progress {
  stroke-dasharray: 377; /* 2π * 60 */
  stroke-dashoffset: calc(377 * (1 - var(--progress)));
  transition: stroke-dashoffset 1s ease-in-out;
}
```

---

### **Ateş Gücü Detayı**
```typescript
interface FirepowerBuild {
  bulletType: {
    current: string; // "Yakhar Ateşi"
    level: number; // 4
    damageMultiplier: number; // 3.5x
    specialEffects: string[]; // ["Yanma", "Patlama"]
    upgradeHistory: {
      level: number;
      acquiredWave: number;
      timestamp: number;
    }[];
  };
  
  towerPower: {
    averageLevel: number; // 12.4
    totalDamage: number; // 15,420
    specialAbilities: {
      name: string;
      count: number;
      effectiveness: number; // %
    }[];
  };
  
  combatEffectiveness: {
    dps: number; // Damage per second
    range: number; // Average range
    accuracy: number; // Hit rate %
    criticalChance: number; // %
  };
}
```

### **Savunma Sistemi Detayı**
```typescript
interface DefenseBuild {
  shieldSystem: {
    globalWallStrength: number;
    shieldTypes: {
      name: string; // "Mithril Kalkanı"
      level: number;
      protection: number;
      durability: number;
    }[];
    coverage: number; // % of battlefield protected
  };
  
  mineField: {
    totalMines: number;
    damage: number;
    radius: number;
    regeneration: boolean;
    specialEffects: string[];
  };
  
  defensiveEffectiveness: {
    damageReduction: number; // %
    repairRate: number;
    survivalTime: number; // seconds
  };
}
```

### **Ekonomi Sistemi Detayı**
```typescript
interface EconomyBuild {
  goldGeneration: {
    baseIncome: number;
    bonusIncome: number;
    totalPerWave: number;
    efficiency: number; // %
  };
  
  investments: {
    totalSpent: number;
    roi: number; // Return on investment %
    bestPurchases: {
      item: string;
      value: number;
      wave: number;
    }[];
  };
  
  resourceManagement: {
    energySystem: {
      capacity: number;
      regeneration: number;
      efficiency: number; // %
    };
    actionSystem: {
      maxActions: number;
      regenTime: number;
      utilization: number; // %
    };
  };
}
```

### **Görsel Tasarım - Build Detayı**
```css
.build-section {
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 12px;
  padding: 16px;
  margin-bottom: 16px;
}

.stat-breakdown {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 0;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.upgrade-timeline {
  display: flex;
  gap: 8px;
  margin-top: 12px;
}

.upgrade-node {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: linear-gradient(45deg, #4ade80, #22c55e);
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-weight: bold;
  font-size: 12px;
  position: relative;
}

.upgrade-node.completed {
  background: linear-gradient(45deg, #ffd700, #ffa500);
}

.upgrade-node::after {
  content: '';
  position: absolute;
  bottom: -24px;
  left: 50%;
  transform: translateX(-50%);
  font-size: 10px;
  color: #888;
}
```

---

### **Seri Tamamlama Takibi**
```typescript
interface AchievementSeries {
  firepower: {
    bulletMastery: {
      name: "Mermi Ustası";
      description: "Tüm mermi tiplerini dene";
      progress: 4; // of 8
      completed: false;
      reward: "Özel mermi efekti";
    };
    towerCommander: {
      name: "Kule Komutanı";
      description: "25 seviyeli kule inşa et";
      progress: 1; // of 1
      completed: true;
      reward: "Efsanevi kule görünümü";
    };
  };
  
  defense: {
    fortressMaster: {
      name: "Kale Ustası";
      description: "10x duvar yükseltmesi al";
      progress: 7; // of 10
      completed: false;
      reward: "+50% duvar gücü";
    };
  };
  
  survival: {
    centurion: {
      name: "Yüzbaşı";
      description: "100 wave'e ulaş";
      progress: 45; // of 100
      completed: false;
      reward: "Prestij sistemi açılır";
    };
  };
}
```

### **Başarı Görseli**
```css
.achievement-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 16px;
}

.achievement-card {
  background: linear-gradient(135deg, #1a1a2e, #16213e);
  border: 2px solid transparent;
  border-radius: 12px;
  padding: 16px;
  position: relative;
  overflow: hidden;
}

.achievement-card.completed {
  border-color: #ffd700;
  box-shadow: 0 0 20px rgba(255, 215, 0, 0.3);
}

.achievement-progress {
  width: 100%;
  height: 8px;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 4px;
  overflow: hidden;
  margin-top: 8px;
}

.achievement-progress-bar {
  height: 100%;
  background: linear-gradient(90deg, #4ade80, #22c55e);
  transition: width 0.5s ease;
}

.achievement-reward {
  position: absolute;
  top: 8px;
  right: 8px;
  background: #ffd700;
  color: #000;
  padding: 4px 8px;
  border-radius: 12px;
  font-size: 10px;
  font-weight: bold;
}
```

---

### **Detaylı Performans Metrikleri**
```typescript
interface DetailedStats {
  combat: {
    totalEnemiesKilled: number;
    damageDealt: number;
    accuracyRate: number; // %
    overkillDamage: number;
    mostEffectiveTower: string;
    favoriteStrategy: string;
  };
  
  economic: {
    totalGoldEarned: number;
    totalGoldSpent: number;
    efficiency: number; // %
    bestInvestment: string;
    wasteLevel: number; // %
  };
  
  survival: {
    longestRun: number; // waves
    totalPlaytime: number; // minutes
    deathCount: number;
    closeCallCount: number; // survived with <10% health
  };
  
  progression: {
    waveCompletionTimes: number[];
    improvementRate: number; // % getting better
    skillLevel: 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert';
  };
}
```

### **Grafik Görselleştirme**
```css
.stats-dashboard {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
}

.stat-chart {
  background: rgba(0, 0, 0, 0.3);
  border-radius: 12px;
  padding: 16px;
  height: 200px;
}

.performance-radar {
  position: relative;
  width: 200px;
  height: 200px;
  margin: 0 auto;
}

.radar-polygon {
  fill: rgba(74, 222, 128, 0.2);
  stroke: #4ade80;
  stroke-width: 2;
}

.stat-trend {
  display: flex;
  align-items: center;
  gap: 8px;
  margin: 8px 0;
}

.trend-arrow {
  width: 0;
  height: 0;
  border-left: 6px solid transparent;
  border-right: 6px solid transparent;
}

.trend-up {
  border-bottom: 8px solid #4ade80;
}

.trend-down {
  border-top: 8px solid #ef4444;
}
```

---

### **Teknoloji Ağacı**
```typescript
interface ResearchTree {
  offense: {
    ballisticTechnology: {
      name: "Balistik Teknolojisi";
      level: 3; // of 5
      effect: "+15% mermi hızı";
      cost: 500; // research points
      unlocked: true;
    };
    explosiveEngineering: {
      name: "Patlayıcı Mühendisliği";
      level: 1; // of 3
      effect: "+25% patlama hasarı";
      cost: 800;
      unlocked: true;
    };
  };
  
  defense: {
    materialScience: {
      name: "Malzeme Bilimi";
      level: 2; // of 4
      effect: "+20% duvar dayanıklılığı";
      cost: 600;
      unlocked: true;
    };
  };
  
  economy: {
    resourceOptimization: {
      name: "Kaynak Optimizasyonu";
      level: 0; // of 3
      effect: "+10% altın verimi";
      cost: 400;
      unlocked: false;
    };
  };
}
```

---

### **AI Destekli Öneriler**
```typescript
interface StrategyAdvisor {
  currentAnalysis: {
    overallRating: 'A' | 'B' | 'C' | 'D' | 'F';
    strengths: string[];
    weaknesses: string[];
    improvements: string[];
  };
  
  nextWaveRecommendations: {
    waveNumber: number;
    difficulty: 'Easy' | 'Medium' | 'Hard' | 'Boss';
    enemyTypes: string[];
    suggestions: {
      priority: 'High' | 'Medium' | 'Low';
      action: string;
      reason: string;
      estimatedCost: number;
    }[];
  };
  
  longTermStrategy: {
    buildDirection: 'Offense' | 'Defense' | 'Balanced' | 'Economic';
    milestones: {
      wave: number;
      target: string;
      progress: number; // %
    }[];
  };
}
```

### **Strateji Görseli**
```css
.strategy-advisor {
  background: linear-gradient(135deg, #1e3a8a, #3730a3);
  border-radius: 16px;
  padding: 20px;
  color: white;
}

.recommendation-card {
  background: rgba(255, 255, 255, 0.1);
  border-left: 4px solid #ffd700;
  border-radius: 8px;
  padding: 12px;
  margin: 8px 0;
}

.priority-high {
  border-left-color: #ef4444;
  background: rgba(239, 68, 68, 0.1);
}

.priority-medium {
  border-left-color: #f59e0b;
  background: rgba(245, 158, 11, 0.1);
}

.priority-low {
  border-left-color: #22c55e;
  background: rgba(34, 197, 94, 0.1);
}

.strategy-radar {
  display: flex;
  justify-content: center;
  margin: 20px 0;
}
```

---

### **Açma/Kapama**
```typescript
// Keyboard shortcut
const handleKeyPress = (event: KeyboardEvent) => {
  if (event.key === 's' || event.key === 'S') {
    if (event.ctrlKey || event.metaKey) return; // Ignore Ctrl+S (save)
    
    event.preventDefault();
    toggleCommandCenter();
  }
  
  if (event.key === 'Escape') {
    closeCommandCenter();
  }
};

// Toggle function
const toggleCommandCenter = () => {
  setCommandCenterOpen(prev => !prev);
  
  // Pause game when opened
  if (!commandCenterOpen) {
    pauseGame();
    playSound('ui-open');
  } else {
    resumeGame();
    playSound('ui-close');
  }
};
```

### **Tab Navigation**
```typescript
// Tab switching
const switchTab = (tabId: string) => {
  setActiveTab(tabId);
  playSound('ui-tab-switch');
  
  // Track analytics
  trackEvent('command_center_tab_switch', {
    from: activeTab,
    to: tabId,
    sessionTime: performance.now() - sessionStartTime
  });
};
```

---

### **Ana Layout**
```css
.command-center-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: rgba(0, 0, 0, 0.85);
  backdrop-filter: blur(10px);
  z-index: 1000;
  display: flex;
  justify-content: center;
  align-items: center;
}

.command-center-window {
  width: 90vw;
  max-width: 1200px;
  height: 85vh;
  background: linear-gradient(135deg, #0f0f23, #1a1a2e, #16213e);
  border: 3px solid #ffd700;
  border-radius: 20px;
  box-shadow: 0 25px 50px rgba(0, 0, 0, 0.5);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.command-center-header {
  background: linear-gradient(90deg, #ffd700, #ffed4a);
  color: #000;
  padding: 16px 24px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.command-center-title {
  font-size: 24px;
  font-weight: bold;
  display: flex;
  align-items: center;
  gap: 12px;
}

.close-button {
  background: rgba(239, 68, 68, 0.2);
  border: 2px solid #ef4444;
  border-radius: 50%;
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s ease;
}

.close-button:hover {
  background: #ef4444;
  color: white;
}
```

### **Tab System**
```css
.tab-navigation {
  display: flex;
  background: rgba(0, 0, 0, 0.3);
  border-bottom: 1px solid rgba(255, 215, 0, 0.3);
}

.tab-button {
  flex: 1;
  padding: 16px 20px;
  background: transparent;
  border: none;
  color: #ccc;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.3s ease;
  position: relative;
}

.tab-button:hover {
  color: #ffd700;
  background: rgba(255, 215, 0, 0.1);
}

.tab-button.active {
  color: #ffd700;
  background: rgba(255, 215, 0, 0.2);
}

.tab-button.active::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 3px;
  background: linear-gradient(90deg, #ffd700, #ffed4a);
}

.tab-content {
  flex: 1;
  padding: 24px;
  overflow-y: auto;
  color: white;
}
```

### **Animasyonlar**
```css
@keyframes slideInFromTop {
  from {
    opacity: 0;
    transform: translateY(-50px) scale(0.9);
  }
  to {
    opacity: 1;
    transform: translateY(0) scale(1);
  }
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.command-center-window {
  animation: slideInFromTop 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94);
}

.tab-content > * {
  animation: fadeInUp 0.3s ease-out;
}

.stat-number {
  transition: all 0.5s ease;
}

.stat-number.updated {
  color: #4ade80;
  transform: scale(1.1);
}
```

---

### **State Management**
```typescript
interface CommandCenterState {
  isOpen: boolean;
  activeTab: string;
  data: {
    overview: PowerOverview;
    builds: {
      firepower: FirepowerBuild;
      defense: DefenseBuild;
      economy: EconomyBuild;
    };
    achievements: AchievementSeries;
    statistics: DetailedStats;
    research: ResearchTree;
    strategy: StrategyAdvisor;
  };
  preferences: {
    defaultTab: string;
    autoUpdate: boolean;
    animationsEnabled: boolean;
  };
}

// Update triggers
const updateCommandCenterData = () => {
  const gameState = useGameStore.getState();
  
  return {
    overview: calculatePowerOverview(gameState),
    builds: analyzeBuildConfiguration(gameState),
    achievements: checkAchievementProgress(gameState),
    statistics: generateDetailedStats(gameState),
    research: getResearchProgress(gameState),
    strategy: generateStrategyAdvice(gameState)
  };
};
```

---

### **Command Center Sesleri**
```typescript
const commandCenterSounds = {
  open: 'command-center-open.wav',      // Yeni ses
  close: 'command-center-close.wav',    // Yeni ses
  tabSwitch: 'ui-tab-switch.wav',       // Yeni ses
  dataUpdate: 'ui-data-refresh.wav',    // Yeni ses
  achievement: 'achievement-ping.wav',   // Yeni ses
  warning: 'strategy-warning.wav',      // Yeni ses
  typing: 'ui-typing.wav'               // Yeni ses
};

// Auto-play on events
const playContextualSound = (event: string) => {
  if (commandCenterSounds[event]) {
    playSound(commandCenterSounds[event]);
  }
};
```

---

### **Faz 1: Temel Yapı (1 hafta)**
- [ ] Modal overlay ve tab sistemi
- [ ] Temel data collection
- [ ] S tuşu kontrol sistemi
- [ ] Minimal Overview tab

### **Faz 2: Veri Zenginleştirme (1 hafta)**
- [ ] Detaylı build analizi
- [ ] Achievement tracking sistemi
- [ ] Statistics calculation
- [ ] Visual components

### **Faz 3: Gelişmiş Özellikler (1 hafta)**
- [ ] Strategy advisor AI
- [ ] Research tree integration
- [ ] Advanced animations
- [ ] Audio system integration

### **Faz 4: Polish & Optimization (3 gün)**
- [ ] Performance optimization
- [ ] Mobile responsiveness
- [ ] User testing feedback
- [ ] Bug fixes

---

### **Functional Requirements**
- [ ] S tuşu ile anında açılır/kapanır
- [ ] 6 tab tam fonksiyonel
- [ ] Real-time data updates
- [ ] Oyun pause olur açıkken
- [ ] Tüm upgrade history görünür

### **User Experience Requirements**
- [ ] <200ms açılma süresi
- [ ] Smooth animations
- [ ] Intuitive navigation
- [ ] Clear information hierarchy
- [ ] Helpful strategic insights

### **Technical Requirements**
- [ ] No performance impact on game
- [ ] Memory efficient
- [ ] Mobile responsive
- [ ] Accessible design
- [ ] Error handling

---

**Sonuç**: Command Center, oyuncuya build'ini analiz etme, progress'ini takip etme ve strategic kararlar alma imkanı verecek. Bu feature tek başına oyunun depth'ini önemli ölçüde artıracak ve player retention'ı iyileştirecek.
